/**
 * Platform lifecycle helpers.
 *
 *   node tools/setup.mjs bootstrap  — after a fresh clone
 *   node tools/setup.mjs resume     — after reboot (DB pod stopped)
 *
 * Does not start the application stack; use `npm run start` / `npm run dev`.
 */
import { copyFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const mode = process.argv[2] ?? "bootstrap";

function log(msg) {
  console.log(`[setup] ${msg}`);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: "inherit",
    env: process.env,
    shell: process.platform === "win32",
    ...options,
  });
  if (result.error) throw result.error;
  if (result.status !== 0 && !options.allowFailure) {
    process.exit(result.status ?? 1);
  }
  return result;
}

function ensureEnvFiles() {
  const pairs = [
    ["apps/backend/.env.example", "apps/backend/.env"],
    ["apps/frontend/.env.example", "apps/frontend/.env"],
  ];
  for (const [example, target] of pairs) {
    const from = resolve(root, example);
    const to = resolve(root, target);
    if (!existsSync(from)) {
      log(`skip missing example: ${example}`);
      continue;
    }
    if (existsSync(to)) {
      log(`env exists: ${target}`);
      continue;
    }
    copyFileSync(from, to);
    log(`created ${target} from ${example}`);
  }
}

function assertAdminRuntimeData() {
  const required = [
    "apps/frontend/public/data/boundaries.geojson",
    "apps/frontend/public/data/manifest.json",
  ];
  const missing = required.filter((p) => !existsSync(resolve(root, p)));
  if (missing.length) {
    console.error(
      `[setup] Missing admin runtime data:\n  ${missing.join("\n  ")}\n` +
        "Generate with tools/data-pipeline/admin-boundaries (see its README).",
    );
    process.exit(1);
  }
  log("admin runtime data present (boundaries + manifest)");
}

function assertSeedInput() {
  const path = "apps/frontend/public/data/signal-quality.json";
  if (!existsSync(resolve(root, path))) {
    console.error(
      `[setup] Missing seed input ${path}.\n` +
        "Generate with: python3 tools/data-pipeline/signal-quality/generate.py",
    );
    process.exit(1);
  }
  log("signal-quality seed input present");
}

function waitForPostgres(maxAttempts = 60) {
  log("waiting for PostgreSQL…");
  for (let i = 1; i <= maxAttempts; i += 1) {
    const result = spawnSync(
      "podman",
      [
        "exec",
        "drone-drive-postgres",
        "pg_isready",
        "-U",
        "postgres",
        "-d",
        "drone_drive",
      ],
      { encoding: "utf8" },
    );
    if (result.status === 0) {
      log("PostgreSQL is ready");
      return;
    }
    if (i === maxAttempts) {
      console.error(
        "[setup] PostgreSQL did not become ready. Check: npm run db:status / db:logs",
      );
      process.exit(1);
    }
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 1000);
  }
}

function dbUp() {
  log("starting database pod…");
  run("node", ["tools/db/podman-db.mjs", "up"]);
  waitForPostgres();
}

function migrate() {
  log("applying migrations (prisma migrate deploy)…");
  run("npm", ["run", "migrate:deploy", "--workspace", "@drone-drive/backend"]);
}

function seed() {
  log("seeding signal quality…");
  run("npm", ["run", "db:seed-signal-quality"]);
  log("seeding demo missions…");
  run("npm", ["run", "db:seed-demo-missions"]);
}

function bootstrap() {
  log("bootstrap (fresh clone)");
  ensureEnvFiles();
  assertAdminRuntimeData();
  assertSeedInput();
  dbUp();
  // Prisma client is generated by postinstall; regenerate in case install skipped it.
  log("generating Prisma client…");
  run("npm", ["run", "db:generate"]);
  migrate();
  seed();
  log("bootstrap complete. Launch with: npm run start");
}

function resume() {
  log("resume (after reboot / stopped DB)");
  ensureEnvFiles();
  dbUp();
  log("resume complete. Launch with: npm run start");
}

if (mode === "bootstrap") bootstrap();
else if (mode === "resume") resume();
else {
  console.error(`Usage: node tools/setup.mjs <bootstrap|resume>`);
  process.exit(1);
}
